# Variáveis

[[exercises]]
name = "variaveis1"
path = "exercises/01_variaveis/variaveis1.rs"
mode = "compile"
hint = """
"""

[[exercises]]
name = "variaveis2"
path = "exercises/01_variaveis/variaveis2.rs"
mode = "compile"
hint = """
"""

# Dono

[[exercises]]
name = "dono1"
path = "exercises/02_dono/dono1.rs"
mode = "compile"
hint = """
"""

[[exercises]]
name = "dono2"
path = "exercises/02_dono/dono2.rs"
mode = "compile"
hint = """
"""

# Referência

[[exercises]]
name = "referencia1"
path = "exercises/03_referencia/referencia1.rs"
mode = "compile"
hint = """
"""

[[exercises]]
name = "referencia2"
path = "exercises/03_referencia/referencia2.rs"
mode = "compile"
hint = """
"""